# Generated by Django 3.1.1 on 2021-08-24 20:55

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=appointment.models.get_date),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(),
        ),
    ]
